### ISSUE TITLE
NOOBS and Raspbian image now includes Minecraft-Pi

### ISSUE THREAD

**Issue by mobluse** [scratch2mcpi/scratch2mcpi.github.io#1]
Now Raspbian via NOOBS and probably the Raspbian image includes Minecraft Pi. That makes it unnecessary to download Minecraft and that would also save space. It would be good if you could update your scripts to take advantage of the built-in Minecraft.

**Comment by champierre** [comment]
Thank you so much for your feedback. I updated the install script to skip Minecraft Pi installation if it is pre-installed, and also updated Readme of https://github.com/scratch2mcpi/scratch2mcpi.
